"""add_auto_escalation_engine

Revision ID: 67b3c50254e5
Revises: e873bd153046
Create Date: 2026-01-11 20:53:03.010930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67b3c50254e5'
down_revision: Union[str, None] = 'e873bd153046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults to avoid null constraint violations on existing rows
    op.add_column('jobs', sa.Column('engine_mode', sa.String(), nullable=False, server_default='auto'))
    op.add_column('jobs', sa.Column('browser_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('runs', sa.Column('engine_attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    
    # Remove server defaults after backfill (we use Python defaults going forward)
    op.alter_column('jobs', 'engine_mode', server_default=None)
    op.alter_column('jobs', 'browser_profile', server_default=None)
    op.alter_column('runs', 'engine_attempts', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'engine_attempts')
    op.drop_column('jobs', 'browser_profile')
    op.drop_column('jobs', 'engine_mode')
    # ### end Alembic commands ###
