"""add_smartfields_support

Revision ID: 7a18db658bb3
Revises: 95e990bdf68b
Create Date: 2026-01-11 21:38:10.364304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a18db658bb3'
down_revision: Union[str, None] = '95e990bdf68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SmartFields columns to field_maps with server_default for existing rows
    op.add_column('field_maps', sa.Column('field_type', sa.String(), nullable=False, server_default='string'))
    op.add_column('field_maps', sa.Column('smart_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('field_maps', sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    
    # Remove server_default after populating existing rows
    op.alter_column('field_maps', 'field_type', server_default=None)
    op.alter_column('field_maps', 'smart_config', server_default=None)
    op.alter_column('field_maps', 'validation_rules', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_maps', 'validation_rules')
    op.drop_column('field_maps', 'smart_config')
    op.drop_column('field_maps', 'field_type')
    op.create_table('domain_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_escalations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_cost_per_record', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domain_stats_pkey'),
    sa.UniqueConstraint('domain', 'engine', name='uq_domain_engine')
    )
    op.create_index('ix_domain_stats_engine', 'domain_stats', ['engine'], unique=False)
    op.create_index('ix_domain_stats_domain', 'domain_stats', ['domain'], unique=False)
    # ### end Alembic commands ###
