"""add_domain_stats_intelligence

Revision ID: 95e990bdf68b
Revises: 67b3c50254e5
Create Date: 2026-01-11 21:12:42.596412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e990bdf68b'
down_revision: Union[str, None] = '67b3c50254e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
