"""add_selector_versioning

Revision ID: 9df2ab06aadc
Revises: 8a354d5e2999
Create Date: 2026-01-11 21:55:09.125935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df2ab06aadc'
down_revision: Union[str, None] = '8a354d5e2999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for existing rows
    op.add_column('field_maps', sa.Column('selector_version', sa.String(), nullable=False, server_default='1'))
    op.add_column('field_maps', sa.Column('selector_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('field_maps', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Remove server_default after populating existing rows
    op.alter_column('field_maps', 'selector_version', server_default=None)
    op.alter_column('field_maps', 'selector_history', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_maps', 'updated_at')
    op.drop_column('field_maps', 'selector_history')
    op.drop_column('field_maps', 'selector_version')
    # ### end Alembic commands ###
