"""add_hitl_intervention_tasks

Revision ID: c42e9567cc74
Revises: 7a18db658bb3
Create Date: 2026-01-11 21:53:04.846704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c42e9567cc74'
down_revision: Union[str, None] = '7a18db658bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_stats_domain', table_name='domain_stats')
    op.drop_index('ix_domain_stats_engine', table_name='domain_stats')
    op.drop_table('domain_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_escalations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_cost_per_record', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domain_stats_pkey'),
    sa.UniqueConstraint('domain', 'engine', name='uq_domain_engine')
    )
    op.create_index('ix_domain_stats_engine', 'domain_stats', ['engine'], unique=False)
    op.create_index('ix_domain_stats_domain', 'domain_stats', ['domain'], unique=False)
    # ### end Alembic commands ###
