"""add_hilr_rule_candidates

Revision ID: c98fac10e668
Revises: 9df2ab06aadc
Create Date: 2026-01-11 21:59:50.446088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c98fac10e668'
down_revision: Union[str, None] = '9df2ab06aadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intervention_job', table_name='intervention_tasks')
    op.drop_index('ix_intervention_status', table_name='intervention_tasks')
    op.drop_table('intervention_tasks')
    op.drop_index('ix_domain_stats_domain', table_name='domain_stats')
    op.drop_index('ix_domain_stats_engine', table_name='domain_stats')
    op.drop_table('domain_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_escalations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_cost_per_record', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domain_stats_pkey'),
    sa.UniqueConstraint('domain', 'engine', name='uq_domain_engine')
    )
    op.create_index('ix_domain_stats_engine', 'domain_stats', ['engine'], unique=False)
    op.create_index('ix_domain_stats_domain', 'domain_stats', ['domain'], unique=False)
    op.create_table('intervention_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='intervention_tasks_job_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name='intervention_tasks_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='intervention_tasks_pkey')
    )
    op.create_index('ix_intervention_status', 'intervention_tasks', ['status'], unique=False)
    op.create_index('ix_intervention_job', 'intervention_tasks', ['job_id'], unique=False)
    # ### end Alembic commands ###
